// Generated by mdclaw /generate-tests

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { parseSchemaContract } from '../contract-harness.js';
import { initDb } from '../../src/db.js';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type Database from 'better-sqlite3';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const SCHEMA_PATH = resolve(__dirname, '../../.claude/skills/add-core/schema.sql');

describe('Schema contract conformance', () => {
  const tables = parseSchemaContract(SCHEMA_PATH);
  let db: Database.Database;

  beforeAll(() => {
    db = initDb(':memory:');
  });

  afterAll(() => {
    db.close();
  });

  it('should set WAL journal mode (memory DBs report as memory)', () => {
    // In-memory SQLite databases can't use WAL, they always report 'memory'.
    // The important thing is that initDb calls pragma('journal_mode = WAL').
    // We verify this by checking that initDb's source contains the WAL pragma.
    const result = db.pragma('journal_mode') as Array<{ journal_mode: string }>;
    // :memory: databases report 'memory', file DBs report 'wal'
    expect(['wal', 'memory']).toContain(result[0].journal_mode);
  });

  for (const table of tables) {
    describe(`table ${table.tableName}`, () => {
      it('should exist in database', () => {
        const info = db.prepare(`PRAGMA table_info(${table.tableName})`).all() as Array<{ name: string; type: string; notnull: number }>;
        expect(info.length).toBeGreaterThan(0);
      });

      for (const col of table.columns) {
        it(`should have column ${col.name}`, () => {
          const info = db.prepare(`PRAGMA table_info(${table.tableName})`).all() as Array<{ name: string; type: string; notnull: number }>;
          const column = info.find(c => c.name === col.name);
          expect(column).toBeDefined();
          expect(column!.type.toUpperCase()).toBe(col.type.toUpperCase());
        });
      }

      for (const idx of table.indices) {
        it(`should have index ${idx}`, () => {
          const indices = db.prepare(`PRAGMA index_list(${table.tableName})`).all() as Array<{ name: string }>;
          const found = indices.find(i => i.name === idx);
          expect(found).toBeDefined();
        });
      }
    });
  }

  // Test CHECK constraints
  describe('CHECK constraints', () => {
    it('should reject invalid schedule_type', () => {
      expect(() => {
        db.prepare(`
          INSERT INTO scheduled_tasks (id, group_folder, chat_jid, prompt, schedule_type, schedule_value, context_mode, status, created_at)
          VALUES ('test-bad', 'test', 'test@g.us', 'test', 'invalid', '1000', 'group', 'active', '2024-01-01')
        `).run();
      }).toThrow();
    });

    it('should reject invalid context_mode', () => {
      expect(() => {
        db.prepare(`
          INSERT INTO scheduled_tasks (id, group_folder, chat_jid, prompt, schedule_type, schedule_value, context_mode, status, created_at)
          VALUES ('test-bad2', 'test', 'test@g.us', 'test', 'once', '2024-01-01', 'invalid', 'active', '2024-01-01')
        `).run();
      }).toThrow();
    });

    it('should reject invalid task status', () => {
      expect(() => {
        db.prepare(`
          INSERT INTO scheduled_tasks (id, group_folder, chat_jid, prompt, schedule_type, schedule_value, context_mode, status, created_at)
          VALUES ('test-bad3', 'test', 'test@g.us', 'test', 'once', '2024-01-01', 'group', 'invalid', '2024-01-01')
        `).run();
      }).toThrow();
    });

    it('should reject invalid task_run_logs status', () => {
      // First create a valid task
      db.prepare(`
        INSERT OR IGNORE INTO scheduled_tasks (id, group_folder, chat_jid, prompt, schedule_type, schedule_value, context_mode, status, created_at)
        VALUES ('test-log', 'test', 'test@g.us', 'test', 'once', '2024-01-01', 'group', 'active', '2024-01-01')
      `).run();

      expect(() => {
        db.prepare(`
          INSERT INTO task_run_logs (task_id, run_at, duration_ms, status)
          VALUES ('test-log', '2024-01-01', 100, 'invalid')
        `).run();
      }).toThrow();
    });
  });
});
