// Generated by mdclaw /generate-tests

import { describe, it, expect } from 'vitest';
import { parseTypesContract } from '../contract-harness.js';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const CONTRACT_PATH = resolve(__dirname, '../../.claude/skills/add-core/types-contract.ts');
const TYPES_PATH = resolve(__dirname, '../../src/types.ts');
const AGENT_RUNNER_PATH = resolve(__dirname, '../../container/agent-runner/src/index.ts');

describe('Types contract conformance', () => {
  const interfaces = parseTypesContract(CONTRACT_PATH);
  const typesSrc = readFileSync(TYPES_PATH, 'utf8');

  for (const iface of interfaces) {
    describe(`interface ${iface.name}`, () => {
      it('should exist in src/types.ts', () => {
        const pattern = new RegExp(`export\\s+interface\\s+${iface.name}\\s*\\{`);
        expect(typesSrc).toMatch(pattern);
      });

      for (const field of iface.fields) {
        it(`should have field ${field.name}`, () => {
          const optionalMarker = field.optional ? '\\??' : '';
          const pattern = new RegExp(`${field.name}${optionalMarker}\\s*[:(]`);
          expect(typesSrc).toMatch(pattern);
        });
      }
    });
  }

  // Also check type aliases
  it('should export OnInboundMessage type', () => {
    expect(typesSrc).toMatch(/export\s+type\s+OnInboundMessage/);
  });

  it('should export OnChatMetadata type', () => {
    expect(typesSrc).toMatch(/export\s+type\s+OnChatMetadata/);
  });

  describe('ContainerInput cross-boundary', () => {
    it('should match between host and agent-runner', () => {
      const agentRunnerSrc = readFileSync(AGENT_RUNNER_PATH, 'utf8');

      // Verify agent-runner expects the same ContainerInput fields
      const contractCI = interfaces.find(i => i.name === 'ContainerInput');
      expect(contractCI).toBeDefined();

      for (const field of contractCI!.fields) {
        // Check that agent-runner references each field
        expect(agentRunnerSrc).toContain(field.name);
      }
    });
  });
});
